### ISSUE TITLE
Add better examples to the documentation

### ISSUE THREAD

**Issue by tcurdt** [bcoe/nyc#134]
Update from moderator:

The biggest issue is that our documentation shows global use of `nyc` without ever suggesting that `nyc` be installed globally.

Original Message:
---
I am not quite sure how the instructions in the README ever worked. `npm i nyc` installs the module just locally and nothing gets added to the path. Calling

    nyc tap ./test/*.js

gives a "command not found" (to no surprise). One would think that

    ./node_modules/nyc/bin/nyc.js tap ./test/*.js

should work. But instead that gives

        $ ./node_modules/nyc/bin/nyc.js tap ./test/*.js
        events.js:141
              throw er; // Unhandled 'error' event
              ^

        Error: spawn tap ENOENT
            at exports._errnoException (util.js:874:11)
            at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
            at onErrorNT (internal/child_process.js:344:16)
            at doNTCallback2 (node.js:439:9)
            at process._tickCallback (node.js:353:17)
            at Function.Module.runMain (module.js:469:11)
            at startup (node.js:134:18)
            at node.js:961:3

**Comment by jamestalmage** [comment]
You need to do:

```
$ ./node_modules/.bin/nyc
```

Note the dot (`.`) in front of `bin`.

**Comment by jamestalmage** [comment]
https://docs.npmjs.com/files/folders#executables

**Comment by bcoe** [comment]
@tcurdt I think it would be worthwhile for us to update the documentation with some additional examples that demonstrate installing, and instrumenting your code with nyc.

**Comment by tcurdt** [comment]
Fair enough:

        $ ./node_modules/.bin/nyc tap ./test/*.js
        events.js:141
              throw er; // Unhandled 'error' event
              ^

        Error: spawn tap ENOENT
            at exports._errnoException (util.js:874:11)
            at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
            at onErrorNT (internal/child_process.js:344:16)
            at doNTCallback2 (node.js:439:9)
            at process._tickCallback (node.js:353:17)
            at Function.Module.runMain (module.js:469:11)
            at startup (node.js:134:18)
            at node.js:961:3

**Comment by tcurdt** [comment]
What works: `./node_modules/.bin/nyc npm test`

**Comment by jamestalmage** [comment]
```
$ ./node_modules/.bin/nyc ./node_modules/.bin/tap test/*.js
````

Or you can install `nyc` and/or `tap` with the `-g` option.

**Comment by tcurdt** [comment]
`./node_modules/.bin/nyc ./node_modules/.bin/tap test/*.js` should go into the docs.

**Comment by novemberborn** [comment]
FWIW I tend to use `$(npm bin)/nyc` and the likes for locally installed dependencies.
