### ISSUE TITLE
does not create output folder

### ISSUE THREAD

**Issue by tcurdt** [bcoe/nyc#136]
if it requires the output folder - it should also create it

        fs.js:813
          return binding.readdir(pathModule._makeLong(path));
                         ^

        Error: ENOENT: no such file or directory, scandir '/path/project/.nyc_output'
            at Error (native)
            at Object.fs.readdirSync (fs.js:813:18)
            at NYC._loadReports (/path/project/node_modules/nyc/index.js:316:18)
            at NYC.report (/path/project/node_modules/nyc/index.js:303:8)
            at report (/path/project/node_modules/nyc/bin/nyc.js:166:7)
            at Object.<anonymous> (/path/project/node_modules/nyc/bin/nyc.js:124:5)
            at Module._compile (module.js:435:26)
            at Object.Module._extensions..js (module.js:442:10)
            at Module.load (module.js:356:32)
            at Function.Module._load (module.js:311:12)

**Comment by jamestalmage** [comment]
From the stack trace, I am guessing you are running `reports` when no coverage information exists.
Perhaps we should provide a better error message - but that should still through don't you agree?

**Comment by tcurdt** [comment]
I would have to cross check if that was the cause. Could be.
Either way - catching this and providing a better error message would be great.

**Comment by bcoe** [comment]
@tcurdt happy to improve this message, I think @jamestalmage is most likely correct about what bit you.

Updating the installation documentation I think would have helped you (and other new folks) avoid this issue as well.
