### ISSUE TITLE
Throws with --babel flag set and no reporter specified

### ISSUE THREAD

**Issue by ben-eb** [bcoe/nyc#141]
```
$ nyc --babel ava src/__tests__/
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at ChildProcess.spawn (/Users/beneb/projects/remark-comment-blocks/node_modules/spawn-wrap/index.js:138:18)
    at exports.spawn (child_process.js:362:9)
    at module.exports (/Users/beneb/projects/remark-comment-blocks/node_modules/foreground-child/index.js:33:15)
    at Object.<anonymous> (/Users/beneb/projects/remark-comment-blocks/node_modules/nyc/bin/nyc.js:144:5)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

Whereas this works perfectly:

```
nyc --babel --reporter=text ava src/__tests__/
```

ref: https://github.com/sindresorhus/ava/pull/444#issuecomment-172315357

**Comment by ben-eb** [comment]
Use `--require` instead of `--babel`.
