### ISSUE TITLE
Fatal error related to esprima when using --all

### ISSUE THREAD

**Issue by MoOx** [bcoe/nyc#173]
```
❯ nyc -a ava

/Users/MoOx/Sync/Development/statinamic/node_modules/esprima/esprima.js:5701
            throw e;
            ^
Error: Line 1: Unexpected token
    at constructError (/Users/MoOx/Sync/Development/statinamic/node_modules/esprima/esprima.js:2406:21)
    at createError (/Users/MoOx/Sync/Development/statinamic/node_modules/esprima/esprima.js:2425:17)
    at unexpectedTokenError (/Users/MoOx/Sync/Development/statinamic/node_modules/esprima/esprima.js:2499:13)
    at tolerateUnexpectedToken (/Users/MoOx/Sync/Development/statinamic/node_modules/esprima/esprima.js:2508:21)
    at parseStatementListItem (/Users/MoOx/Sync/Development/statinamic/node_modules/esprima/esprima.js:3972:21)
    at parseFunctionSourceElements (/Users/MoOx/Sync/Development/statinamic/node_modules/esprima/esprima.js:4868:23)
    at parseFunctionExpression (/Users/MoOx/Sync/Development/statinamic/node_modules/esprima/esprima.js:5073:16)
    at parsePrimaryExpression (/Users/MoOx/Sync/Development/statinamic/node_modules/esprima/esprima.js:3272:24)
    at inheritCoverGrammar (/Users/MoOx/Sync/Development/statinamic/node_modules/esprima/esprima.js:2680:18)
    at parseLeftHandSideExpressionAllowCall (/Users/MoOx/Sync/Development/statinamic/node_modules/esprima/esprima.js:3413:20)
```

The same command works without --all. 
Stack trace is not clear for me.
Any idea?

I am using some es6, ava handle the require hook, maybe I should add it too with nyc?

**Comment by MoOx** [comment]
I confirm that using `nyc --require babel-core/register -a ava` is a workaround. Maybe we should get a more clear reason of the error?

**Comment by novemberborn** [comment]
`--all` loads and instruments all `.js` files before launching AVA. It might be loading files containing syntax that Istanbul cannot parse. Using the `--require` flag on nyc itself allows those files to be loaded.

So yea you're doing the right thing. I've opened #175 to improve the error.

Please reopen if you have further questions.
