### ISSUE TITLE
Error report is broken

### ISSUE THREAD

**Issue by TrySound** [bcoe/nyc#182]
I have uncought expection in tests. Position and part of code are broken. I use tape for tests.
Error with nyc
```
D:\_host\github\css-calc-eval\lib\tokenize.js:9
kfswZa$BeA.b['8'][1]++;__cov_66bSrHn0dnVfkfswZa$BeA.s['82']++;throw new CSSCal
                                                                    ^
Error
    at Object.<anonymous> (D:\_host\github\css-calc-eval\lib\CSSCalcError.js:9:384)
    at Module._compile (module.js:460:26)
    at Module.replacementCompile (D:\_host\github\css-calc-eval\node_modules\append-transform\index.js:53:13)
    at Module._extensions..js (module.js:478:10)
    at Object.<anonymous> (D:\_host\github\css-calc-eval\node_modules\append-transform\index.js:57:4)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\_host\github\css-calc-eval\lib\tokenize.js:9:56)
```
without
```
D:\_host\github\css-calc-eval\lib\tokenize.js:119
                        throw new CSSCalcError(pos, unexpectedInput);
                              ^
Error
    at Object.<anonymous> (D:\_host\github\css-calc-eval\lib\CSSCalcError.js:8:26)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\_host\github\css-calc-eval\lib\tokenize.js:1:82)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by novemberborn** [comment]
@TrySound nyc uses [Istanbul](https://github.com/gotwarlost/istanbul) to instrument the files. This changes the code that is actually run. As you found running without nyc gives you a more usable stack trace. Use that for debugging, and nyc for computing the code coverage.

#168 talks about Istanbul generating source maps for its instrumentation. If it did that you could combine with <https://github.com/evanw/node-source-map-support> and get stack traces for the actual source.
