### ISSUE TITLE
nyc npm test --all

### ISSUE THREAD

**Issue by reggi** [bcoe/nyc#244]
Running into an issue when I use the `--all` flag.

```
thomasreggi@zx:estore-payments$ nyc npm test --all

/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/nyc/node_modules/esprima/esprima.js:5701
            throw e;
            ^
Error: Line 1: Unexpected token
    at constructError (/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/nyc/node_modules/esprima/esprima.js:2406:21)
    at createError (/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/nyc/node_modules/esprima/esprima.js:2425:17)
    at unexpectedTokenError (/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/nyc/node_modules/esprima/esprima.js:2499:13)
    at tolerateUnexpectedToken (/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/nyc/node_modules/esprima/esprima.js:2508:21)
    at parseStatementListItem (/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/nyc/node_modules/esprima/esprima.js:3972:21)
    at parseFunctionSourceElements (/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/nyc/node_modules/esprima/esprima.js:4868:23)
    at parseFunctionExpression (/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/nyc/node_modules/esprima/esprima.js:5073:16)
    at parsePrimaryExpression (/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/nyc/node_modules/esprima/esprima.js:3272:24)
    at inheritCoverGrammar (/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/nyc/node_modules/esprima/esprima.js:2680:18)
    at parseLeftHandSideExpressionAllowCall (/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/nyc/node_modules/esprima/esprima.js:3413:20)
```

**Comment by reggi** [comment]
EYEGOTIT.

`nf run -- nyc --all --require babel-core/register --require babel-polyfill npm test`

**Comment by bcoe** [comment]
@reggi \o/
