### ISSUE TITLE
Wrong result of default parameters.

### ISSUE THREAD

**Issue by mysticatea** [bcoe/nyc#261]
I encountered a case my test's result is changed by nyc.
What am I going to wrong?

- Windows 7 Pro
- Git Shell (of GitHub Desktop)
- Node 6.1.0
- npm 3.9.0
- nyc 6.4.4
- mocha 2.3.4

```js
test_dir
 ├ foo.js
 └ test.js
```

**foo.js**

```js
"use strict";

module.exports = function foo({a = 0, b = 1} = {}) {
    return a + b;
};
```

**test.js**

```js
"use strict";

const assert = require("assert");
const foo = require("./foo");

describe("test", () => {
    it("test", () => {
        assert.strictEqual(foo(), 1);
        assert.strictEqual(foo({a: 1}), 2);
    });
});
```

**Commands**

```
> node node_modules/mocha/bin/_mocha test.js

  test
    √ test

  1 passing (8ms)

> nyc node_modules/mocha/bin/_mocha test.js

  test
    1) test


  0 passing (9ms)
  1 failing

  1) test test:

      AssertionError: NaN === 1
      + expected - actual

      -NaN
      +1

      at Context.it (C:\...\test.js:8:16)
      at callFn (C:\...\node_modules\mocha\lib\runnable.js:315:21)
      at Test.Runnable.run (C:\...\node_modules\mocha\lib\runnable.js:308:7)
      at Runner.runTest (C:\...\node_modules\mocha\lib\runner.js:422:10)
      at C:\...\node_modules\mocha\lib\runner.js:533:12
      at next (C:\...\node_modules\mocha\lib\runner.js:342:14)
      at C:\...\node_modules\mocha\lib\runner.js:352:7
      at next (C:\...\node_modules\mocha\lib\runner.js:284:14)
      at Immediate._onImmediate (C:\...\node_modules\mocha\lib\runner.js:320:5)



-----------|----------|----------|----------|----------|----------------|
File       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------|----------|----------|----------|----------|----------------|
 test_dir\ |      100 |      100 |      100 |      100 |                |
  foo.js   |      100 |      100 |      100 |      100 |                |
-----------|----------|----------|----------|----------|----------------|
All files  |      100 |      100 |      100 |      100 |                |
-----------|----------|----------|----------|----------|----------------|

```

**Comment by novemberborn** [comment]
@mysticatea are you using any transpilers at all or are you running this as-is? If the latter, I suspect Istanbul, the library we use to instrument your code, is having trouble with the ES6 syntax. You'll have to transpile to ES5. Hopefully that'll give you better results (though it means code coverage has to rely on source maps which isn't foolproof).

**Comment by mysticatea** [comment]
Thank you for the clarify.
I'm sad that I still need transpilers even if I'm using Node 6. :cry:

**Comment by bcoe** [comment]
@mysticatea agreed this would be nice to fix! I know @novemberborn has been putting some work into an ES6 code-coverage solution, which would help solve this problem.

**Comment by holm** [comment]
This seems to be the underlying problem: https://github.com/gotwarlost/istanbul/issues/613
