### ISSUE TITLE
regressions with source-map-cache

### ISSUE THREAD

**Issue by bcoe** [bcoe/nyc#271]
https://github.com/bcoe/nyc/commit/0838a0e5e2ce8d7ae636655e3832cd318aaaaf95 seems to introduce a regression with source-map mapping with the `yarsay` project:

```sh
> yarsay@1.0.5 posttest /Users/benjamincoe/bcoe/yarsay
> nyc report --reporter lcov --reporter text

/Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/report/html.js:276
                startCol = meta.start.column;
                               ^

TypeError: Cannot read property 'start' of undefined
    at /Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/report/html.js:276:32
    at Array.forEach (native)
    at annotateBranches (/Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/report/html.js:255:30)
    at HtmlReport.Report.mix.writeDetailPage (/Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/report/html.js:426:9)
    at /Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/report/html.js:489:26
    at SyncFileWriter.extend.writeFile (/Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.extend.writeFile (/Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/report/html.js:488:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/report/html.js:482:23)
```

_recreate by:_

1. [cloning `yarsay`](https://github.com/yargs/yarsay).
2. cloning `nyc` at `master`.
3. linking `nyc` into `yarsay` and running tests: `rm -rf node_modules/.cache/; rm -rf .nyc_output/; npm t`.

There is a separate issue with the refactoring work that has been done on https://github.com/bcoe/nyc/pull/268:

```sh
> nyc report --reporter lcov --reporter text

/Users/benjamincoe/bcoe/yarsay/node_modules/nyc/node_modules/istanbul/lib/report/html.js:241
            text = structuredText[startLine].text;
                                            ^

TypeError: Cannot read property 'text' of undefined
    at /Users/benjamincoe/bcoe/yarsay/node_modules/nyc/node_modules/istanbul/lib/report/html.js:241:45
    at Array.forEach (native)
    at annotateFunctions (/Users/benjamincoe/bcoe/yarsay/node_modules/nyc/node_modules/istanbul/lib/report/html.js:224:26)
    at HtmlReport.Report.mix.writeDetailPage (/Users/benjamincoe/bcoe/yarsay/node_modules/nyc/node_modules/istanbul/lib/report/html.js:427:9)
    at /Users/benjamincoe/bcoe/yarsay/node_modules/nyc/node_modules/istanbul/lib/report/html.js:489:26
    at SyncFileWriter.extend.writeFile (/Users/benjamincoe/bcoe/yarsay/node_modules/nyc/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.extend.writeFile (/Users/benjamincoe/bcoe/yarsay/node_modules/nyc/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /Users/benjamincoe/bcoe/yarsay/node_modules/nyc/node_modules/istanbul/lib/report/html.js:488:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/Users/benjamincoe/bcoe/yarsay/node_modules/nyc/node_modules/istanbul/lib/report/html.js:482:23)
npm ERR! Test failed.  See above for more details.
```

_recreate by:_

1. [cloning `yarsay`](https://github.com/yargs/yarsay).
2. installing nyc at `next`: `npm i nyc@next`
3. running tests: `rm -rf node_modules/.cache/; rm -rf .nyc_output/; npm t`.

Any thoughts, @novemberborn? I'd love to get to the point where we can land #268 without any regressions, so that we can start transitioning folks towards `__coverage__` in the future.

**Comment by bcoe** [comment]
@novemberborn fixed here:

**Comment by novemberborn** [comment]
@bcoe you mean <https://github.com/bcoe/nyc/pull/268/commits/5063825ba96bf2c2f60967eb88c20b32d0985a9c>?

I'm not sure how that relates to my earlier changes though.
