### ISSUE TITLE
[Question] CoffeeScript integration

### ISSUE THREAD

**Issue by Kikobeats** [bcoe/nyc#273]
I don't know If I'm doing something bad, but coffeescript hook isn't working on my project.

Basically I run my test with:

```
nyc --require coffee-script/register mocha
```

and everything looks well

```
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
----------|----------|----------|----------|----------|----------------|
All files |      100 |      100 |      100 |      100 |                |
----------|----------|----------|----------|----------|----------------|
```

but nothing is written at nyc folder. any idea?

**Comment by bcoe** [comment]
@Kikobeats by default nyc looks for the extension `.js`, do you need to set `--extension coffee`?

Let me know if this works, would be happy to add a blurb to the docs about coffeescript.

**Comment by Kikobeats** [comment]
yay, now is working! https://coveralls.io/github/bumped/bumped

Effectively is necessary provide extension:

```
nyc --extension .coffee mocha
```

I don't need register the transpiler because I register it in mocha options.

Thanks!

**Comment by zhaoxiongfei** [comment]
```
Cannot read property 'text' of undefined
TypeError: Cannot read property 'text' of undefined
    at /root/.nvm/versions/node/v6.2.2/lib/node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:96:45
    at Array.forEach (native)
    at annotateFunctions (/root/.nvm/versions/node/v6.2.2/lib/node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:79:26)
    at Object.annotateSourceCode (/root/.nvm/versions/node/v6.2.2/lib/node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:192:9)
    at HtmlReport.onDetail (/root/.nvm/versions/node/v6.2.2/lib/node_modules/nyc/node_modules/istanbul-reports/lib/html/index.js:217:39)
    at LcovReport.(anonymous function) [as onDetail] (/root/.nvm/versions/node/v6.2.2/lib/node_modules/nyc/node_modules/istanbul-reports/lib/lcov/index.js:24:24)
    at Visitor.(anonymous function) [as onDetail] (/root/.nvm/versions/node/v6.2.2/lib/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/root/.nvm/versions/node/v6.2.2/lib/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:123:17)
    at /root/.nvm/versions/node/v6.2.2/lib/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:116:23
    at Array.forEach (native)
```

locv report error.
