### ISSUE TITLE
bundled `foreground-child`'s dependency `cross-spawn-async` is missing dep

### ISSUE THREAD

**Issue by terinjokes** [bcoe/nyc#279]
`foreground-child`'s dependency `cross-spawn-async` depends on `which` which is declared in the package.json, but unresolvable at runtime.

```

module.js:328
    throw err;
    ^

Error: Cannot find module 'which'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/terinjokes/promise-series/node_modules/nyc/node_modules/foreground-child/node_modules/cross-spawn-async/lib/resolveCommand.js:4:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

**Comment by bcoe** [comment]
@terinjokes could you `npm clear` and try `nyc@6.6.1`?

**Comment by terinjokes** [comment]
@bcoe seems fine now.
