### ISSUE TITLE
Incorrect? coverage report with child_process.exec

### ISSUE THREAD

**Issue by Janpot** [bcoe/nyc#55]
I'm trying out `nyc` on my project https://github.com/Janpot/fantastiq with `nyc npm test` which yields:

```
-----------------|----------|----------|----------|----------|----------------|
File             |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------------|----------|----------|----------|----------|----------------|
 bin/            |      100 |      100 |      100 |      100 |                |
  fantastiq.js   |      100 |      100 |      100 |      100 |                |
 lib/            |    29.05 |    10.98 |     8.21 |    29.11 |                |
  Queue.js       |    39.73 |       20 |     12.5 |       40 |... 412,416,420 |
  QueueClient.js |    51.11 |        0 |       10 |    51.11 |... 50,52,58,59 |
  Worker.js      |    15.19 |        0 |        0 |    15.19 |... 131,134,139 |
  index.js       |    56.52 |      100 |    16.67 |    56.52 |... 29,30,31,37 |
  jobUtils.js    |    30.43 |     7.14 |       25 |    30.43 |... 36,38,39,40 |
  message.js     |       12 |        0 |        0 |       12 |... 32,33,34,39 |
  metrics.js     |    41.67 |       25 |    33.33 |    41.67 |... 32,33,34,37 |
  router.js      |    10.91 |        0 |        0 |    10.91 |... 247,253,255 |
-----------------|----------|----------|----------|----------|----------------|
All files        |    35.44 |    15.85 |    16.33 |    35.51 |                |
-----------------|----------|----------|----------|----------|----------------|
```

This looked very odd to me as I expected my coverage to be closer to 100%. Checking out some of the lines I was sure they were all called in my tests. After some trial and error I found that after skipping some tests I get the (hopefully) correct coverage:

```
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
----------|----------|----------|----------|----------|----------------|
All files |      100 |      100 |      100 |      100 |                |
----------|----------|----------|----------|----------|----------------|
```

The tests I skipped were https://github.com/Janpot/fantastiq/blob/master/test/cli.spec.js#L13 (`describe.skip(...`)

This part of the code runs some commands with `child_process.exec`.

If you want to try this out you'll need to have a redis running somewhere, if it's not at `127.0.0.1` you can specify one with the `REDIS_HOST` variable.

**Comment by Janpot** [comment]
And doing the same with the `--all` option gives more different results:

cli tests enabled:

```
-----------------|----------|----------|----------|----------|----------------|
File             |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------------|----------|----------|----------|----------|----------------|
 bin/            |      100 |      100 |      100 |      100 |                |
  fantastiq.js   |      100 |      100 |      100 |      100 |                |
 examples/       |     3.23 |        0 |        0 |     3.23 |                |
  basic.js       |     3.23 |        0 |        0 |     3.23 |... 58,59,61,68 |
 lib/            |    29.48 |    10.98 |     8.15 |    29.55 |                |
  Queue.js       |    41.33 |       20 |     12.5 |    41.61 |... 414,418,422 |
  QueueClient.js |    51.11 |        0 |       10 |    51.11 |... 50,52,58,59 |
  Worker.js      |    15.19 |        0 |        0 |    15.19 |... 131,134,139 |
  index.js       |    56.52 |      100 |    16.67 |    56.52 |... 29,30,31,37 |
  jobUtils.js    |    30.43 |     7.14 |       25 |    30.43 |... 36,38,39,40 |
  message.js     |       12 |        0 |        0 |       12 |... 32,33,34,39 |
  metrics.js     |    41.67 |       25 |    33.33 |    41.67 |... 31,32,33,36 |
  router.js      |    10.91 |        0 |        0 |    10.91 |... 237,243,245 |
  util.js        |    16.67 |      100 |        0 |    16.67 |     4,5,6,8,11 |
-----------------|----------|----------|----------|----------|----------------|
All files        |    33.93 |    15.51 |    15.48 |    33.99 |                |
-----------------|----------|----------|----------|----------|----------------|
```

cli tests skipped:

```
-----------------|----------|----------|----------|----------|----------------|
File             |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------------|----------|----------|----------|----------|----------------|
 bin/            |     4.26 |        0 |        0 |     4.26 |                |
  fantastiq.js   |     4.26 |        0 |        0 |     4.26 |... 133,134,136 |
 examples/       |     3.23 |        0 |        0 |     3.23 |                |
  basic.js       |     3.23 |        0 |        0 |     3.23 |... 58,59,61,68 |
 lib/            |     4.33 |        0 |        0 |     4.34 |                |
  Queue.js       |     0.67 |        0 |        0 |     0.67 |... 421,422,425 |
  QueueClient.js |     6.67 |        0 |        0 |     6.67 |... 72,73,74,76 |
  Worker.js      |      3.8 |        0 |        0 |      3.8 |... 134,139,142 |
  index.js       |    13.04 |        0 |        0 |    13.04 |... 34,36,37,40 |
  jobUtils.js    |    17.39 |        0 |        0 |    17.39 |... 38,39,40,43 |
  message.js     |        8 |        0 |        0 |        8 |... 33,34,39,44 |
  metrics.js     |     4.17 |        0 |        0 |     4.17 |... 33,36,40,41 |
  router.js      |     2.73 |        0 |        0 |     2.73 |... 245,248,249 |
  util.js        |    16.67 |      100 |        0 |    16.67 |     4,5,6,8,11 |
-----------------|----------|----------|----------|----------|----------------|
All files        |     4.26 |        0 |        0 |     4.27 |                |
-----------------|----------|----------|----------|----------|----------------|
```

**Comment by bcoe** [comment]
@Janpot I will need to dig into how the babel step in your test-suite works, I'm guessing this is where something is getting lost in translation.

**Comment by bcoe** [comment]
@Janpot both babel-registry, and nyc override `require`:

https://github.com/babel/babel/blob/master/packages/babel-register/src/node.js#L99

I'm starting to dig, and will see if I can get them to play nice together :+1:

**Comment by Janpot** [comment]
thanks for looking into this.

**Comment by bcoe** [comment]
@Janpot it might be useful if you'd chime in on this pull request:

https://github.com/babel/babel/pull/3062

I'm trying to convince the maintainers of babel, that it would be great to expose a hook for other libraries to instrument the babel-compiled code.

**Comment by bcoe** [comment]
@Janpot a work in progress (needs more tests and some code cleanup), but give this a shot:

https://github.com/bcoe/nyc/commit/334e479bd0db7ef476b844dd53a55fa0ca6b952c

<img width="591" alt="screen shot 2015-11-24 at 11 37 17 pm" src="https://cloud.githubusercontent.com/assets/194609/11391112/e15f74f8-9304-11e5-8dc1-807ecda56050.png">

It adds support for babel using:

* a more complicated approach to overriding the require extension.
* fancy source-map shenanigans.

**Comment by Janpot** [comment]
Thanks, looking good.

I'll give it a shot when I work on this again

**Comment by bcoe** [comment]
@Janpot `nyc@4.x` is now out the door with Babel support. I've written this blog post on the topic:

https://github.com/polyglotweekly/polyglotweekly.com/pull/15

**Comment by Janpot** [comment]
@bcoe Thanks, I'm trying it out but running into other babel issues first.

**Comment by Janpot** [comment]
@bcoe Finally got around to testing this. It seems the `--all` option is broken for me now.

without it I get the coverage report but when I enable it I get a 

```sh
~/fantastiq/node_modules/istanbul/lib/object-utils.js:247
            for (i = 0; i < retArray.length; i += 1) {
                                    ^

TypeError: Cannot read property 'length' of undefined
    at ~/fantastiq/node_modules/istanbul/lib/object-utils.js:247:37
    at Array.forEach (native)
    at Object.mergeFileCoverage (~/fantastiq/node_modules/istanbul/lib/object-utils.js:244:31)
    at ~/fantastiq/node_modules/istanbul/lib/collector.js:71:44
    at Array.forEach (native)
    at Object.Collector.add (~/fantastiq/node_modules/istanbul/lib/collector.js:68:31)
    at ~/fantastiq/node_modules/nyc/index.js:213:15
    at Array.forEach (native)
    at NYC.report (~/fantastiq/node_modules/nyc/index.js:212:23)
    at report (~/fantastiq/node_modules/nyc/bin/nyc.js:137:7)
```
